### PR TITLE
fix: fix credit list data, and run format

### PR DESCRIPTION
**Pull request by idax6797**
This pull request includes changes to the `CreditsList` component and a minor adjustment to the `AdvancedSearchForm` CSS. The most important changes involve improving the handling of media items in the `CreditsList` component by adding a default image and updating references to media properties.

Improvements to CreditsList component:

* [`src/frontend/src/components/CreditsList/CreditsList.jsx`](diffhunk://#diff-79ac5aa8333eaa37aae7dc4f49e1730687820b2e92ff2be356bee92754b48c43L4-R4): Added `DefaultImage` component to handle cases where `media.posterUri` is not available.
* [`src/frontend/src/components/CreditsList/CreditsList.jsx`](diffhunk://#diff-79ac5aa8333eaa37aae7dc4f49e1730687820b2e92ff2be356bee92754b48c43R14-R31): Updated references to media properties, such as changing `item.posterUri` to `item.media.posterUri` and `item.title` to `item.media.title`.
* [`src/frontend/src/components/CreditsList/CreditsList.jsx`](diffhunk://#diff-79ac5aa8333eaa37aae7dc4f49e1730687820b2e92ff2be356bee92754b48c43L46-R52): Changed column header from "Character name" to "Role" for clarity.

Minor CSS adjustment:

* [`src/frontend/src/components/AdvancedSearchForm/AdvancedSearchForm.css`](diffhunk://#diff-415375fa2d6bdbeaa445a81787ffad4ace0aab85a637025a2b17866d93dc4b5eL41): Removed trailing whitespace for cleaner code formatting.

### CODE REVIEW

**Review by sofushn — CHANGES_REQUESTED** [review]
I think we should group episodes into a series instead with a count of how many episodes they are in

This is 'Christian Bale' (240)
image

Something like this maybe
image

**Comment by idax6797** [comment]
> I think we should group episodes into a series instead with a count of how many episodes they are in
> 
> This is 'Christian Bale' (240) image
> 
> Something like this maybe image

Yes, this is have looked at so we do not have the serie that ties them together, returned.  How should i then go about it?
Screenshot 2024-12-13 at 16 20 00

**Comment by sofushn** [comment]
> Yes, this is have looked at so we do not have the serie that ties them together, returned. How should i then go about it? 

Ahh we dont... I'll add this to the api tonight then, lets just let this PR wait for little while longer

**Comment by sofushn** [comment]
> Yes, this is have looked at so we do not have the serie that ties them together, returned. How should i then go about it? 

Ahh we dont... I'll add this to the api tonight then, lets just let this PR wait for little while longer

**Comment by sofushn** [comment]
Only some of the episodes are loaded at once, I think it would make sense to load all episodes for a series at once, and also only have a show all button instead of show more that have to be clicked multiple times

**Review by sofushn — APPROVED** [review]

**Pull request merged**
